version: "2"

services:
  gitea:
    image: gitea/gitea:1.21.4-rootless
    restart: always
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"

volumes:
  gitea-data:
    name: gitea-data
    external: false
  gitea-config:
    name: gitea-config
    external: false
